name: run-script.yaml

on:
  push:
    branches: main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install dependencies if you have a DESCRIPTION file
      - uses: r-lib/actions/setup-r-dependencies@v2

      # Run your script
      - name: Run scrape_news.R
        run: Rscript R/scrape_news.R
